
// This file is auto-generated by generate-build-version.js
// Do not edit directly.
export const APP_VERSION = "0.1.0";
export const BUILD_HASH = "65e070e";
export const BUILD_DATE = "12/5/2025 9:42:53 PM";
