
// This file is auto-generated by generate-build-version.js
// Do not edit directly.
export const APP_VERSION = "0.1.0";
export const BUILD_HASH = "7e8d1aa";
export const BUILD_DATE = "12/7/2025 3:49:08 PM";
